version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai-chatbot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ai-chatbot
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatbot-network

  redis:
    image: redis:7.2-alpine
    container_name: ai-chatbot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chatbot-network

volumes:
  mongodb_data:
  redis_data:

networks:
  chatbot-network:
    driver: bridge
